services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      KUBERNETES_APIS: https://control-api-v1.22.1-control-plane:6443/apis/
networks:
  default:
    external: true
    name: kind
