environments:
  preview: {}
  integration: {}

repositories:
  - name: appuio
    # If testing out a feature branch of the Helm chart, export variable:
    # `export CHART_REPO_URL="git+https://github.com/appuio/charts@appuio/cloud-portal?ref=<your-feature-branch>"`
    url: "{{ env "CHART_REPO_URL" | default "https://charts.appuio.ch" }}"

helmDefaults:
  historyMax: 3

releases:
  - name: "{{ env "HELM_RELEASE_NAME" | default "portal" }}"
    chart: appuio/cloud-portal
    version: v0.2.0
    createNamespace: false
    missingFileHandler: Warn
    values:
      - "{{ .Environment.Name }}.yaml"
      - image:
          tag: {{ trimPrefix "refs/tags/" (requiredEnv "IMG_TAG") }}
      - fullnameOverride: {{ env "HELM_RELEASE_NAME" | default "portal" }}
      - podAnnotations:
          app.kubernetes.io/git-shasum: {{ env "GIT_SHA" | default "GIT_SHA" }}
      - portal:
          config:
            version: {{ env "GIT_SHA" | default "GIT_SHA" }}
