apiVersion: v1
clusters:
  - cluster:
      server: https://api.appuio.cloud/
    name: control-api
contexts:
  - context:
      cluster: control-api
      namespace: default
      user: oidc-user
    name: Default
current-context: Default
kind: Config
preferences: {}
users:
  - name: oidc-user
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://id.vshn.net/auth/realms/vshn-realm
          - --oidc-client-id=appuio_control-api
          - --oidc-extra-scope=email offline_access profile openid
        command: kubectl
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false
