name: Master

on:
  push:
    branches:
      - master

env:
  REGISTRY: registry.cloudscale-lpg-2.appuio.cloud
  NAMESPACE: appuio-control-api-integration
  IMAGE_NAME: cloud-portal

jobs:

  build:
    uses: appuio/cloud-portal/.github/workflows/template-build.yaml@master

  docker:
    runs-on: ubuntu-latest
    environment: integration
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          # by default, it creates the `:pr-#` tag in pull requests and branch name on `master`
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE}}/${{ env.IMAGE_NAME }}

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    uses: appuio/cloud-portal/.github/workflows/template-deploy.yaml@master
    with:
      namespace: appuio-control-api-integration
      image_tag: master
      revision: ${{ github.sha }}
      environment: integration
    secrets:
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      glitch_tip_dsn: ${{ secrets.GLITCH_TIP_DSN }}
    needs:
      - build
      - docker
