on:
  workflow_call:
    inputs:
      namespace:
        type: string
        required: true
      helm_release_name:
        type: string
        default: portal
        required: false
      image_tag:
        type: string
        required: true
      revision:
        type: string
        required: true
      environment:
        type: string
        required: false
        default: preview
    secrets:
      openshift_token:
        required: true
      keycloak_user:
        required: false
      keycloak_password:
        required: false
      glitch_tip_dsn:
        required: true

env:
  OPENSHIFT_API: https://api.cloudscale-lpg-2.appuio.cloud:6443

jobs:
  install:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ steps.deployment_info.outputs.route_host }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          helm-version: v3.11.2
          helmfile-version: v0.152.0
          install-kubectl: false
          additional-helm-plugins: https://github.com/aslafy-z/helm-git --version 0.15.1

      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_API }}
          openshift_token: ${{ secrets.openshift_token }}
          namespace: ${{ inputs.namespace }}
          # We don't have a LE cert yet
          insecure_skip_tls_verify: true

      - name: Deploy app
        run: helmfile --namespace ${{ inputs.namespace }} --file deployment/helmfile.yaml -e ${{ inputs.environment }} apply --wait
        env:
          HELM_RELEASE_NAME: ${{ inputs.helm_release_name }}
          IMG_TAG: ${{ inputs.image_tag }}
          GIT_SHA: ${{ inputs.revision }}
          GLITCH_TIP_DSN: ${{ secrets.glitch_tip_dsn }}
          ENVIRONMENT: preview-${{ inputs.image_tag }}

      - name: Gather deployment status
        id: deployment_info
        run: |
          echo route_host="$(oc -n ${{ inputs.namespace }} get route ${{ inputs.helm_release_name }} -o jsonpath='{.spec.host}')" >> $GITHUB_OUTPUT

      - name: Add route URL to Keycloak client
        if: ${{ github.event_name == 'pull_request' }}
        run: .github/keycloak-redirect-url.sh "${{ secrets.keycloak_user }}" "${{ secrets.keycloak_password }}" "https://${{ steps.deployment_info.outputs.route_host }}"

      - name: Notify on success
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ## 🚀 Preview deployment active

            | | |
            |-|-|
            **App URL** | https://${{ steps.deployment_info.outputs.route_host }}
            **Revision** | ${{ inputs.revision }}
            **Helm release** | ${{ inputs.namespace }}/${{ inputs.helm_release_name }}
            **Cluster** | ${{ env.OPENSHIFT_API }}

            To uninstall this deployment, close or merge this PR.
