on:
  workflow_call: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run test

  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  e2e:
    runs-on: ubuntu-latest
    needs:
      - dist
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: cypress-io/github-action@v5
        with:
          start: npm run http-server
          # workaround so that Cypress runs with the system node version rather than action's configured node version.
          # https://github.com/cypress-io/github-action/issues/489#issuecomment-1021379037
          command-prefix: "--"
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-videos
          path: cypress/videos
